#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch H2b1 — move the `.sf-explore` band's CSS out of configurator.css.

Three things in here are not obvious, and each one is a trap this project has
already fallen into at least once:

  * **The delete is done in place, in the same commit as the insert.** style.css
    is enqueued at functions.php:31, configurator.css at :188 — the later file
    wins at equal specificity. Migrating the rules without deleting the originals
    leaves the old declarations silently overriding the new ones: no error, no
    console warning, just a page that ignores the edit. So the originals go, and
    gate S4 re-counts rule heads on both sides to prove it.

  * **Rule heads, not occurrences.** `sf-explore__chip` also appears in two
    style.css *comments* ("Geometry mirrors .sf-explore__chip …"), so a raw
    substring count reports six hits for a class that has no rule at all.
    Comments are stripped first, and the unit of comparison is a rule head.

  * **The re-scoped band is a different component.** The old comment says the
    pills are sized small "so all 8 fit on a single row in the 65%-wide options
    column at 1440px". That column no longer exists — the band is its own
    full-width section now — so the comment is rewritten and the pills go back
    to the site's 14px chip scale. Keeping a comment that describes a layout
    that was deleted is how the next reader gets misled.

usage:
    python3 tools/b2d_h2b1_css.py --check
    python3 tools/b2d_h2b1_css.py --apply
"""

import argparse
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
THEME = os.path.join(ROOT, 'sinofresh-theme')
CFG = os.path.join(THEME, 'assets', 'css', 'configurator.css')
STY = os.path.join(THEME, 'style.css')
FUN = os.path.join(THEME, 'functions.php')

# The block to migrate: from the section comment to the end of the
# prefers-reduced-motion query, 125 lines (833-957). It is located by content
# and confirmed by the line numbers, never sliced by the numbers alone.
BLOCK_FIRST = '/* === Explore more dosage forms (cross-sell band) =========================='
BLOCK_LAST = '}'
BLOCK_LINES = 125

NEW_HEADER = '''/* === 59. Explore more dosage forms band (dosage pages, H2b1) ==============
   Cross-sell band: a pill per dosage form plus an outline CTA to the full
   product list. Batch H2b1 moved it out of the configurator's options column
   into its own section on the eight dosage pages — between the Standard
   Formulas band and How We Work — so it spans the full content column now
   instead of 65% of it. That is why the pills are back at the site's 14px chip
   scale: the "as tight as possible so all eight fit one row" sizing only ever
   existed to survive the narrow column, and the 6px radius stays because these
   are navigation tags, not multi-select chips. */'''

CHIPS_COMMENT_OLD = '''/* Outline pills generated by the [sf_explore_chips] shortcode. They reuse
   the configurator option-button look (6px radius, hairline border) so the
   band and the configurator above read as one component. Sized one notch
   tighter than the option buttons so all 8 fit on a single row in the
   65%-wide options column at 1440px. */'''
CHIPS_COMMENT_NEW = '''/* Outline pills generated by the [sf_explore_chips] shortcode. Hairline
   border and 6px radius, one notch tighter than the option buttons, and back
   at the 14px chip scale now that the band is full width. */'''

# (old, new, label) — every one must match exactly once inside the block.
EDITS = [
    ('.sf-explore {\n\tmargin-top: 24px;', '.sf-explore {\n\tmargin-top: 0;',
     'band margin-top zeroed (it is a standalone section now)'),
    (CHIPS_COMMENT_OLD, CHIPS_COMMENT_NEW, 'chips comment re-scoped'),
    ('\tgap: 6px;', '\tgap: 8px;', 'chips gap 6 -> 8px'),
    ('\tpadding: 8px 12px;', '\tpadding: 10px 16px;', 'chip padding 8/12 -> 10/16px'),
    ('\tfont-size: 13px;\n\tline-height: 1.4;\n\tcolor: var(--wp--preset--color--text-primary);',
     '\tfont-size: 14px;\n\tline-height: 1.4;\n\tcolor: var(--wp--preset--color--text-primary);',
     'chip font-size 13 -> 14px'),
    ('\t.sf-explore {\n\t\tmargin-top: 20px;\n\t\tpadding: 24px;\n\t}',
     '\t.sf-explore {\n\t\tpadding: 24px;\n\t}',
     'mobile margin-top dropped with the margin it belonged to'),
]

MIGRATION_HEADER_OLD = (BLOCK_FIRST + '\n   Sits at the end of the options column — after the last '
                        'dimension group,\n   before the summary card — echoing the Standard '
                        'Formulas band: light\n   grey-green surface, deep ink-green heading, '
                        'outline CTA. */')

# The mobile compensation block that existed only to close the gap down to the
# configurator. With the block gone, `.sf-formulas` goes back to its template
# inline padding and `#configurator` is a dead selector.
COMP_RULE = '.sf-formulas { padding-bottom: 0 !important; }'
COMP_DEAD = '#configurator { padding-top: 32px !important; }'

VER_EDIT = [
    (FUN, "wp_enqueue_style('sinofresh-style', get_stylesheet_uri(), array(), '2.10.55');",
     "wp_enqueue_style('sinofresh-style', get_stylesheet_uri(), array(), '2.10.56');",
     'functions.php style ver 2.10.55 -> 2.10.56'),
    (STY, '\nVersion: 2.10.55\n', '\nVersion: 2.10.56\n',
     'style.css header ver 2.10.55 -> 2.10.56'),
    (FUN, "'/assets/css/configurator.css', array(), '2.9'",
     "'/assets/css/configurator.css', array(), '2.10'",
     'configurator.css ver 2.9 -> 2.10 (its contents changed)'),
]

CLASS_TOKENS = ['sf-explore', 'sf-explore__title', 'sf-explore__chips',
                'sf-explore__chip', 'sf-explore__btn']

COMMENT = re.compile(r'/\*.*?\*/', re.S)

# `php` is not on PATH in this shell; LocalWP ships one under Application
# Support. Linting is a Python call-away, so a missing binary must degrade to a
# notice — not to a traceback that aborts the read-back after the writes landed.
PHP_CANDIDATES = [
    os.environ.get('PHP', ''),
    os.path.expanduser('~/Library/Application Support/Local/lightning-services/'
                       'php-8.2.29+0/bin/darwin-arm64/bin/php'),
    '/opt/homebrew/bin/php',
    '/usr/local/bin/php',
    '/usr/bin/php',
]


def php_binary():
    for c in PHP_CANDIDATES:
        if c and os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return None


def read(p):
    with open(p, encoding='utf-8') as fh:
        return fh.read()


def write(p, s):
    with open(p, 'w', encoding='utf-8') as fh:
        fh.write(s)


def strip_comments(css):
    return COMMENT.sub('', css)


def rule_heads(css):
    """Every rule head, one per selector, with comments removed."""
    out = []
    for raw in re.findall(r'([^{}]+)\{', strip_comments(css)):
        s = raw.strip()
        if s and not s.startswith('@'):
            out.append(s)
    return out


def family_heads(css):
    """Rule heads that select one of the `.sf-explore*` classes."""
    hits = []
    for h in rule_heads(css):
        toks = set()
        for cls in re.findall(r'\.([A-Za-z][\w-]*)', h):
            toks.add(cls)
        if toks & set(CLASS_TOKENS):
            hits.append(h)
    return hits


def brace_balance(css):
    body = strip_comments(css)
    return body.count('{') - body.count('}')


def locate_block(lines):
    idx = [i for i, l in enumerate(lines) if l == BLOCK_FIRST]
    if len(idx) != 1:
        return None, 'section header appears %d times' % len(idx)
    i0 = idx[0]
    i1 = i0 + BLOCK_LINES - 1
    if i1 >= len(lines):
        return None, 'block runs past the end of the file'
    if lines[i1] != BLOCK_LAST:
        return None, 'L%d is %r, expected the closing brace' % (i1 + 1, lines[i1])
    if lines[i1 + 1].strip() != '':
        return None, 'L%d is not blank' % (i1 + 2)
    if lines[i0 - 1].strip() != '':
        return None, 'L%d (above the header) is not blank' % i0
    return (i0, i1), ''


def locate_comp(lines):
    hits = [i for i, l in enumerate(lines) if 'Tighten Standard Formulas -> configurator gap' in l]
    if len(hits) != 1:
        return None, 'compensation comment appears %d times' % len(hits)
    mid = hits[0]
    start = mid
    while start > 0 and lines[start].strip() != '@media (max-width: 768px) {':
        start -= 1
    if lines[start].strip() != '@media (max-width: 768px) {':
        return None, 'no @media (max-width: 768px) { above the compensation comment'
    depth = 0
    end = None
    for j in range(start, len(lines)):
        depth += lines[j].count('{') - lines[j].count('}')
        if depth == 0 and j > start:
            end = j
            break
    if end is None:
        return None, 'the compensation block never closes'
    body = '\n'.join(lines[start:end + 1])
    if COMP_RULE not in body or COMP_DEAD not in body:
        return None, 'the compensation block is not the one declared'
    return (start, end), ''


def transform(block_text):
    text = block_text
    if MIGRATION_HEADER_OLD not in text:
        return None, 'the migration header comment is not the declared text'
    text = text.replace(MIGRATION_HEADER_OLD, NEW_HEADER, 1)
    for old, new, label in EDITS:
        n = text.count(old)
        if n != 1:
            return None, '%s: pattern matched %d times' % (label, n)
        text = text.replace(old, new, 1)
    return text, ''


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--check', action='store_true')
    g.add_argument('--apply', action='store_true')
    args = ap.parse_args(argv)

    cfg = read(CFG)
    sty = read(STY)
    cfg_lines = cfg.split('\n')
    sty_lines = sty.split('\n')

    fails = []

    # ---- preconditions ---------------------------------------------------
    span, err = locate_block(cfg_lines)
    if err:
        fails.append('configurator.css: ' + err)
    comp, err = locate_comp(sty_lines)
    if err:
        fails.append('style.css: ' + err)

    if not fails:
        i0, i1 = span
        block_text = '\n'.join(cfg_lines[i0:i1 + 1])
        print('configurator.css: block L%d-L%d (%d lines, %d bytes)'
              % (i0 + 1, i1 + 1, i1 - i0 + 1, len(block_text.encode())))
        if ':has(' in block_text:
            fails.append('the block contains :has( — the :has() ledger would move')
        new_block, err = transform(block_text)
        if err:
            fails.append('transform: ' + err)
        else:
            print('transform: %d -> %d lines' % (len(cfg_lines[i0:i1 + 1]),
                                                 len(new_block.split('\n'))))
        c0, c1 = comp
        print('style.css: compensation block L%d-L%d (%d lines)' % (c0 + 1, c1 + 1, c1 - c0 + 1))

        before = family_heads(cfg)
        print('configurator.css: %d .sf-explore* rule head(s) to move' % len(before))
        stray = family_heads(sty)
        if stray:
            fails.append('style.css already defines %d .sf-explore* head(s): %s'
                         % (len(stray), stray[:2]))
        for f, old, new, label in VER_EDIT:
            n = read(f).count(old)
            if n != 1:
                fails.append('%s: matched %d times' % (label, n))
            else:
                print('ver anchor OK: %s' % label)
        print('ledger: style.css :has( = %d, configurator.css :has( = %d'
              % (sty.count(':has('), cfg.count(':has(')))

    if fails:
        for f in fails:
            print('  FAIL %s' % f)
        print('\nCHECK FAILED — nothing written.')
        return 1

    if not args.check:
        # ---- write -------------------------------------------------------
        # Drop the block plus the single blank line that followed it, keeping
        # the one that preceded it: the section boundary stays a one-blank-line
        # boundary instead of growing an extra one.
        cfg_new = '\n'.join(cfg_lines[:i0] + cfg_lines[i1 + 2:])
        write(CFG, cfg_new)

        sty_new_lines = sty_lines[:c0] + sty_lines[c1 + 1:]
        appended = '\n' + new_block + '\n'
        write(STY, '\n'.join(sty_new_lines) + appended)

        for f, old, new, label in VER_EDIT:
            text = read(f)
            if text.count(old) != 1:
                print('  FAIL %s no longer matches once' % label)
                return 1
            write(f, text.replace(old, new, 1))

        # ---- read back ---------------------------------------------------
        print('\n--- read back ---')
        cfg2 = read(CFG)
        sty2 = read(STY)
        errs = []
        if family_heads(cfg2):
            errs.append('configurator.css still has %d .sf-explore* head(s)'
                        % len(family_heads(cfg2)))
        if len(family_heads(sty2)) != len(before) or set(family_heads(sty2)) != set(before):
            errs.append('style.css heads %d != %d moved, or the head set changed'
                        % (len(family_heads(sty2)), len(before)))
        if '#configurator' in sty2:
            errs.append('style.css still mentions #configurator')
        if '#configurator' in cfg2:
            errs.append('configurator.css still mentions #configurator')
        if brace_balance(cfg2) != 0:
            errs.append('configurator.css braces unbalanced (%+d)' % brace_balance(cfg2))
        if brace_balance(sty2) != 0:
            errs.append('style.css braces unbalanced (%+d)' % brace_balance(sty2))
        for needle in ('Version: 2.10.56',):
            if needle not in sty2:
                errs.append('style.css missing %r' % needle)
        fun2 = read(FUN)
        for needle in ("'2.10.56'", "'/assets/css/configurator.css', array(), '2.10'"):
            if needle not in fun2:
                errs.append('functions.php missing %r' % needle)
        php = php_binary()
        if php is None:
            print('  note: no php binary found — `php -l functions.php` skipped')
        else:
            lint = subprocess.run([php, '-l', FUN], capture_output=True, text=True)
            if lint.returncode != 0:
                errs.append('php -l functions.php: %s'
                            % (lint.stdout.strip() or lint.stderr.strip()))
            else:
                print('php -l functions.php: %s' % lint.stdout.strip())

        print('configurator.css %d -> %d lines' % (len(cfg_lines), len(cfg2.split('\n'))))
        print('style.css        %d -> %d lines' % (len(sty_lines), len(sty2.split('\n'))))
        print('style.css :has(  %d -> %d' % (sty.count(':has('), sty2.count(':has(')))
        print('configurator.css :has( %d -> %d' % (cfg.count(':has('), cfg2.count(':has(')))
        for e in errs:
            print('  FAIL %s' % e)
        if errs:
            return 1
        print('\nAPPLIED and read back clean.')
        return 0

    print('\nanchors OK; nothing written (--check).')
    return 0


if __name__ == '__main__':
    sys.exit(main())
